use super::shared::{
    log_action, merge_frontmatter, read_visible_entry, write_raw_if_changed, MarkdownDoc,
};
use super::{ExecutionMode, LogMode};
use crate::history::HistoryRecorder;
use crate::markers::{is_relay_generated_command_skill, RELAY_COMMAND_SKILL_MARKER};
use std::collections::{BTreeSet, HashSet};
use std::fs;
use std::io;
use std::path::Path;

pub(super) fn command_skill_name(command_name: &str) -> Option<&str> {
    command_name
        .strip_suffix(".md")
        .filter(|name| !name.is_empty())
}

fn codex_command_skill_frontmatter(skill_name: &str) -> String {
    format!(
        "---\nname: {skill_name}\ndescription: Synced relay command. Use when the user asks to run the {skill_name} workflow.\n---\n"
    )
}

pub(crate) fn sync_codex_command_skill_wrapper(
    source: &MarkdownDoc,
    codex_skills_dir: &Path,
    command_name: &str,
    log_mode: LogMode,
    mode: ExecutionMode,
    history: &mut Option<HistoryRecorder>,
    reserved_skill_names: &HashSet<String>,
) -> io::Result<bool> {
    let Some(skill_name) = command_skill_name(command_name) else {
        return Ok(false);
    };
    let skill_dir = codex_skills_dir.join(skill_name);
    let skill_path = skill_dir.join("SKILL.md");
    let marker_path = skill_dir.join(RELAY_COMMAND_SKILL_MARKER);
    let label = format!("commands: codex skill {}", skill_path.display());

    if reserved_skill_names.contains(skill_name) {
        log_action(
            log_mode,
            &format!("{label}: skipped; real skill owns this name"),
        );
        return Ok(false);
    }

    if skill_dir.exists() && !is_relay_generated_command_skill(&skill_dir) {
        log_action(
            log_mode,
            &format!("{label}: skipped existing non-relay skill"),
        );
        return Ok(false);
    }

    let frontmatter = codex_command_skill_frontmatter(skill_name);
    let contents = merge_frontmatter(Some(&frontmatter), &source.body);
    let marker = b"generated by relay from commands\n";

    if mode == ExecutionMode::Plan {
        let skill_would_change = fs::read(&skill_path).ok().as_deref() != Some(contents.as_bytes());
        let marker_would_change = fs::read(&marker_path).ok().as_deref() != Some(marker);
        if skill_would_change || marker_would_change {
            log_action(log_mode, &format!("{label}: would update"));
            return Ok(true);
        }
        return Ok(false);
    }

    let marker_changed = write_raw_if_changed(&marker_path, marker, mode, history)?;
    let skill_changed = write_raw_if_changed(&skill_path, contents.as_bytes(), mode, history)?;
    if skill_changed || marker_changed {
        log_action(log_mode, &format!("{label}: updated"));
    }
    Ok(skill_changed || marker_changed)
}

pub(crate) fn prune_stale_codex_command_skill_wrappers(
    codex_skills_dir: &Path,
    active_command_names: &BTreeSet<String>,
    log_mode: LogMode,
    mode: ExecutionMode,
    history: &mut Option<HistoryRecorder>,
) -> io::Result<usize> {
    if !codex_skills_dir.exists() {
        return Ok(0);
    }

    let mut removed = 0usize;
    for entry in fs::read_dir(codex_skills_dir)? {
        let entry = entry?;
        let Some((skill_name, skill_dir, meta)) = read_visible_entry(entry, false)? else {
            continue;
        };
        if !meta.is_dir() || !is_relay_generated_command_skill(&skill_dir) {
            continue;
        }

        let command_name = format!("{skill_name}.md");
        if active_command_names.contains(&command_name) {
            continue;
        }

        let label = format!("commands: codex skill {}", skill_dir.display());
        if mode == ExecutionMode::Plan {
            log_action(log_mode, &format!("{label}: would remove"));
            removed += 1;
            continue;
        }

        let before = history
            .as_ref()
            .map(|recorder| recorder.capture_path(&skill_dir))
            .transpose()?;
        fs::remove_dir_all(&skill_dir)?;
        if let Some(recorder) = history.as_mut() {
            let after = recorder.capture_path(&skill_dir)?;
            recorder.record_change(
                &skill_dir,
                before.unwrap_or_else(crate::history::EntityState::missing),
                after,
            );
        }
        log_action(log_mode, &format!("{label}: removed"));
        removed += 1;
    }
    Ok(removed)
}

#[cfg(test)]
mod tests {
    use crate::markers::RELAY_COMMAND_SKILL_MARKER;
    use crate::sync::commands::sync_commands;
    use crate::sync::test_support::{setup, write_plain};
    use crate::sync::LogMode;
    use std::fs;
    use std::io;

    #[test]
    fn sync_codex_command_skill_skips_existing_non_relay_skill() -> io::Result<()> {
        let (_tmp, cfg) = setup()?;

        let skill_path = cfg.codex_skills_dir.join("review/SKILL.md");
        let marker_path = cfg
            .codex_skills_dir
            .join(format!("review/{RELAY_COMMAND_SKILL_MARKER}"));
        let user_content = "---\nname: review\ndescription: user skill\n---\nUser-owned body";
        write_plain(&skill_path, user_content)?;

        let central = cfg.central_dir.join("review.md");
        write_plain(&central, "Central command body.")?;

        sync_commands(&cfg, LogMode::Quiet)?;

        assert_eq!(fs::read_to_string(skill_path)?, user_content);
        assert!(!marker_path.exists());
        Ok(())
    }

    #[test]
    fn sync_commands_creates_codex_skill_wrapper() -> io::Result<()> {
        let (_tmp, cfg) = setup()?;

        let central = cfg.central_dir.join("review.md");
        write_plain(&central, "Review the implementation.")?;

        sync_commands(&cfg, LogMode::Quiet)?;

        let skill = cfg.codex_skills_dir.join("review/SKILL.md");
        let body = fs::read_to_string(skill)?;
        assert!(body.contains("name: review"));
        assert!(body.contains("description: Synced relay command."));
        assert!(body.contains("Review the implementation."));
        assert!(cfg
            .codex_skills_dir
            .join(format!("review/{RELAY_COMMAND_SKILL_MARKER}"))
            .exists());
        Ok(())
    }
}
